package com.example.weatherapp.util

val cities = listOf(
    // United States
    "New York - US",
    "Los Angeles - US",
    "Chicago - US",
    "Houston - US",
    "Phoenix - US",
    "Philadelphia - US",
    "San Antonio - US",
    "San Diego - US",
    "Dallas - US",
    "San Jose - US",

    // Canada
    "Toronto - CA",
    "Vancouver - CA",
    "Montreal - CA",
    "Calgary - CA",
    "Ottawa - CA",
    "Edmonton - CA",
    "Quebec City - CA",
    "Winnipeg - CA",
    "Hamilton - CA",
    "Victoria - CA",

    // United Kingdom
    "London - GB",
    "Birmingham - GB",
    "Manchester - GB",
    "Glasgow - GB",
    "Liverpool - GB",
    "Bristol - GB",
    "Sheffield - GB",
    "Leeds - GB",
    "Edinburgh - GB",
    "Cardiff - GB",

    // Australia
    "Sydney - AU",
    "Melbourne - AU",
    "Brisbane - AU",
    "Perth - AU",
    "Adelaide - AU",
    "Gold Coast - AU",
    "Canberra - AU",
    "Newcastle - AU",
    "Wollongong - AU",
    "Hobart - AU",

    // Germany
    "Berlin - DE",
    "Munich - DE",
    "Hamburg - DE",
    "Cologne - DE",
    "Frankfurt - DE",
    "Stuttgart - DE",
    "Düsseldorf - DE",
    "Dortmund - DE",
    "Essen - DE",
    "Leipzig - DE",

    // France
    "Paris - FR",
    "Marseille - FR",
    "Lyon - FR",
    "Toulouse - FR",
    "Nice - FR",
    "Nantes - FR",
    "Strasbourg - FR",
    "Montpellier - FR",
    "Bordeaux - FR",
    "Lille - FR",

    // Japan
    "Tokyo - JP",
    "Osaka - JP",
    "Yokohama - JP",
    "Nagoya - JP",
    "Sapporo - JP",
    "Fukuoka - JP",
    "Kobe - JP",
    "Kyoto - JP",
    "Kawasaki - JP",
    "Hiroshima - JP",

    // Brazil
    "São Paulo - BR",
    "Rio de Janeiro - BR",
    "Salvador - BR",
    "Fortaleza - BR",
    "Belo Horizonte - BR",
    "Brasília - BR",
    "Manaus - BR",
    "Curitiba - BR",
    "Recife - BR",
    "Porto Alegre - BR",

    // India
    "Mumbai - IN",
    "Delhi - IN",
    "Bengaluru - IN",
    "Hyderabad - IN",
    "Ahmedabad - IN",
    "Chennai - IN",
    "Kolkata - IN",
    "Pune - IN",
    "Jaipur - IN",
    "Surat - IN",

    // China
    "Beijing - CN",
    "Shanghai - CN",
    "Guangzhou - CN",
    "Shenzhen - CN",
    "Chengdu - CN",
    "Wuhan - CN",
    "Hangzhou - CN",
    "Nanjing - CN",
    "Xi'an - CN",
    "Dongguan - CN",

    // Russia
    "Moscow - RU",
    "Saint Petersburg - RU",
    "Novosibirsk - RU",
    "Yekaterinburg - RU",
    "Nizhny Novgorod - RU",
    "Kazan - RU",
    "Chelyabinsk - RU",
    "Samara - RU",
    "Omsk - RU",
    "Rostov-on-Don - RU",

    // Mexico
    "Mexico City - MX",
    "Guadalajara - MX",
    "Monterrey - MX",
    "Puebla - MX",
    "Tijuana - MX",
    "León - MX",
    "Mérida - MX",
    "Cancún - MX",
    "Toluca - MX",
    "Querétaro - MX",

    // Italy
    "Rome - IT",
    "Milan - IT",
    "Naples - IT",
    "Turin - IT",
    "Palermo - IT",
    "Genoa - IT",
    "Bologna - IT",
    "Florence - IT",
    "Catania - IT",
    "Venice - IT",

    // South Africa
    "Johannesburg - ZA",
    "Cape Town - ZA",
    "Durban - ZA",
    "Pretoria - ZA",
    "Port Elizabeth - ZA",
    "East London - ZA",
    "Bloemfontein - ZA",
    "Polokwane - ZA",
    "Nelspruit - ZA",
    "Kimberley - ZA",

    // Argentina
    "Buenos Aires - AR",
    "Córdoba - AR",
    "Rosario - AR",
    "Mendoza - AR",
    "La Plata - AR",
    "Tucumán - AR",
    "Mar del Plata - AR",
    "Salta - AR",
    "Santa Fe - AR",
    "San Juan - AR",

    // Indonesia
    "Jakarta - ID",
    "Surabaya - ID",
    "Bandung - ID",
    "Medan - ID",
    "Semarang - ID",
    "Makassar - ID",
    "Palembang - ID",
    "Tangerang - ID",
    "Batam - ID",
    "Depok - ID",

    // Saudi Arabia
    "Riyadh - SA",
    "Jeddah - SA",
    "Mecca - SA",
    "Medina - SA",
    "Dammam - SA",
    "Khobar - SA",
    "Dhahran - SA",
    "Tabuk - SA",
    "Buraidah - SA",
    "Khamis Mushait - SA",

    // Egypt
    "Cairo - EG",
    "Alexandria - EG",
    "Giza - EG",
    "Shubra El Kheima - EG",
    "Port Said - EG",
    "Suez - EG",
    "Luxor - EG",
    "Aswan - EG",
    "Mansoura - EG",
    "Tanta - EG",
    "Ismailia - EG",
    "Faisal - EG",
    "Damanhur - EG",
    "Zagazig - EG",
    "6th of October City - EG",
    "Al Mahallah Al Kubra - EG",
    "Kafr El Sheikh - EG",
    "Qena - EG",
    "Beni Suef - EG",
    "Minya - EG",
    "Sohag - EG",

    // Vietnam
    "Hanoi - VN",
    "Ho Chi Minh City - VN",
    "Da Nang - VN",
    "Haiphong - VN",
    "Nha Trang - VN",
    "Can Tho - VN",
    "Bien Hoa - VN",
    "Hue - VN",
    "Vung Tau - VN",
    "Bac Ninh - VN",

    // Philippines
    "Quezon City - PH",
    "Manila - PH",
    "Davao City - PH",
    "Cebu City - PH",
    "Zamboanga City - PH",
    "Antipolo - PH",
    "Pasig - PH",
    "Taguig - PH",
    "General Santos - PH",
    "Iloilo City - PH",

    // Thailand
    "Bangkok - TH",
    "Nonthaburi - TH",
    "Nakhon Ratchasima - TH",
    "Chiang Mai - TH",
    "Hat Yai - TH",
    "Khon Kaen - TH",
    "Nakhon Si Thammarat - TH",
    "Udon Thani - TH",
    "Rayong - TH",
    "Pattaya - TH",

    // Turkey
    "Istanbul - TR",
    "Ankara - TR",
    "Izmir - TR",
    "Bursa - TR",
    "Adana - TR",
    "Gaziantep - TR",
    "Konya - TR",
    "Antalya - TR",
    "Kayseri - TR",
    "Mersin - TR",

    // Iran
    "Tehran - IR",
    "Mashhad - IR",
    "Isfahan - IR",
    "Karaj - IR",
    "Tabriz - IR",
    "Shiraz - IR",
    "Ahvaz - IR",
    "Qom - IR",
    "Kermanshah - IR",
    "Urmia - IR",

    // Colombia
    "Bogotá - CO",
    "Medellín - CO",
    "Cali - CO",
    "Barranquilla - CO",
    "Cartagena - CO",
    "Cúcuta - CO",
    "Bucaramanga - CO",
    "Pereira - CO",
    "Santa Marta - CO",
    "Manizales - CO",

    // Sweden
    "Stockholm - SE",
    "Gothenburg - SE",
    "Malmo - SE",
    "Uppsala - SE",
    "Linköping - SE",
    "Västerås - SE",
    "Örebro - SE",
    "Helsingborg - SE",
    "Jönköping - SE",
    "Norrköping - SE",

    // Norway
    "Oslo - NO",
    "Bergen - NO",
    "Stavanger - NO",
    "Drammen - NO",
    "Fredrikstad - NO",
    "Porsgrunn - NO",
    "Sandnes - NO",
    "Skien - NO",
    "Bodø - NO",
    "Larvik - NO",
    //UAE
    "Abu Dhabi - AE",
    "Dubai - AE",
    "Sharjah - AE",
    "Ajman - AE",
    "Ras Al Khaimah - AE",
    "Fujairah - AE",
    "Umm Al-Quwain - AE",
    "Al Ain - AE",
    "Khalifa City - AE",
    "Jebel Ali - AE",

    // Sudan
    "Khartoum - SD",
    "Omdurman - SD",
    "Nyala - SD",
    "Port Sudan - SD",
    "Kassala - SD",
    "El Obeid - SD",
    "Wad Madani - SD",
    "Bahr el Ghazal - SD",
    "Atbara - SD",
    "Kosti - SD",

    // Ethiopia
    "Addis Ababa - ET",
    "Dire Dawa - ET",
    "Mekelle - ET",
    "Gondar - ET",
    "Bahir Dar - ET",
    "Jimma - ET",
    "Awasa - ET",
    "Adama - ET",
    "Nazret - ET",
    "Shashemene - ET",

    // Yemen
    "Sana'a - YE",
    "Aden - YE",
    "Taiz - YE",
    "Al Hudaydah - YE",
    "Ibb - YE",
    "Dhamar - YE",
    "Mukalla - YE",
    "Al Mukalla - YE",
    "Lahij - YE",
    "Al Bayda - YE",

    //Italy
    "Rome - IT",
    "Milan - IT",
    "Naples - IT",
    "Turin - IT",
    "Palermo - IT",
    "Genoa - IT",
    "Bologna - IT",
    "Florence - IT",
    "Catania - IT",
    "Venice - IT",


    // South africa
    "Johannesburg - ZA",
    "Cape Town - ZA",
    "Durban - ZA",
    "Pretoria - ZA",
    "Port Elizabeth - ZA",
    "Bloemfontein - ZA",
    "East London - ZA",
    "Pietermaritzburg - ZA",
    "Tshwane - ZA",
    "Kimberley - ZA",

    //Greece
    "Athens - GR",
    "Thessaloniki - GR",
    "Patras - GR",
    "Heraklion - GR",
    "Larissa - GR",
    "Volos - GR",
    "Rhodes - GR",
    "Ioannina - GR",
    "Kalamata - GR",
    "Chania - GR",

    //Ecudor

    "Quito - EC",
    "Guayaquil - EC",
    "Cuenca - EC",
    "Machala - EC",
    "Loja - EC",
    "Ambato - EC",
    "Manta - EC",
    "Durán - EC",
    "Esmeraldas - EC",
    "Santo Domingo - EC",

    // Cuba
    "Havana - CU",
    "Santiago de Cuba - CU",
    "Camagüey - CU",
    "Holguín - CU",
    "Guantánamo - CU",
    "Santa Clara - CU",
    "Bayamo - CU",
    "Cienfuegos - CU",
    "Las Tunas - CU",
    "Matanzas - CU",


    "Afghanistan - AF",
    "Albania - AL",
    "Algeria - DZ",
    "Andorra - AD",
    "Angola - AO",
    "Antigua and Barbuda - AG",
    "Argentina - AR",
    "Armenia - AM",
    "Australia - AU",
    "Austria - AT",
    "Azerbaijan - AZ",
    "Bahamas - BS",
    "Bahrain - BH",
    "Bangladesh - BD",
    "Barbados - BB",
    "Belarus - BY",
    "Belgium - BE",
    "Belize - BZ",
    "Benin - BJ",
    "Bhutan - BT",
    "Bolivia - BO",
    "Bosnia and Herzegovina - BA",
    "Botswana - BW",
    "Brazil - BR",
    "Brunei - BN",
    "Bulgaria - BG",
    "Burkina Faso - BF",
    "Burundi - BI",
    "Cabo Verde - CV",
    "Cambodia - KH",
    "Cameroon - CM",
    "Canada - CA",
    "Central African Republic - CF",
    "Chad - TD",
    "Chile - CL",
    "China - CN",
    "Colombia - CO",
    "Comoros - KM",
    "Congo, Democratic Republic of the - CD",
    "Congo, Republic of the - CG",
    "Costa Rica - CR",
    "Croatia - HR",
    "Cuba - CU",
    "Cyprus - CY",
    "Czech Republic - CZ",
    "Denmark - DK",
    "Djibouti - DJ",
    "Dominica - DM",
    "Dominican Republic - DO",
    "Ecuador - EC",
    "Egypt - EG",
    "El Salvador - SV",
    "Equatorial Guinea - GQ",
    "Eritrea - ER",
    "Estonia - EE",
    "Eswatini - SZ",
    "Ethiopia - ET",
    "Fiji - FJ",
    "Finland - FI",
    "France - FR",
    "Gabon - GA",
    "Gambia - GM",
    "Georgia - GE",
    "Germany - DE",
    "Ghana - GH",
    "Greece - GR",
    "Grenada - GD",
    "Guatemala - GT",
    "Guinea - GN",
    "Guinea-Bissau - GW",
    "Guyana - GY",
    "Haiti - HT",
    "Honduras - HN",
    "Hungary - HU",
    "Iceland - IS",
    "India - IN",
    "Indonesia - ID",
    "Iran - IR",
    "Iraq - IQ",
    "Ireland - IE",
    "Italy - IT",
    "Jamaica - JM",
    "Japan - JP",
    "Jordan - JO",
    "Kazakhstan - KZ",
    "Kenya - KE",
    "Kiribati - KI",
    "Korea, North - KP",
    "Korea, South - KR",
    "Kuwait - KW",
    "Kyrgyzstan - KG",
    "Laos - LA",
    "Latvia - LV",
    "Lebanon - LB",
    "Lesotho - LS",
    "Liberia - LR",
    "Libya - LY",
    "Liechtenstein - LI",
    "Lithuania - LT",
    "Luxembourg - LU",
    "Madagascar - MG",
    "Malawi - MW",
    "Malaysia - MY",
    "Maldives - MV",
    "Mali - ML",
    "Malta - MT",
    "Marshall Islands - MH",
    "Mauritania - MR",
    "Mauritius - MU",
    "Mexico - MX",
    "Micronesia - FM",
    "Moldova - MD",
    "Monaco - MC",
    "Mongolia - MN",
    "Montenegro - ME",
    "Morocco - MA",
    "Mozambique - MZ",
    "Myanmar - MM",
    "Namibia - NA",
    "Nauru - NR",
    "Nepal - NP",
    "Netherlands - NL",
    "New Zealand - NZ",
    "Nicaragua - NI",
    "Niger - NE",
    "Nigeria - NG",
    "North Macedonia - MK",
    "Norway - NO",
    "Oman - OM",
    "Pakistan - PK",
    "Palau - PW",
    "Palestine - PS",
    "Panama - PA",
    "Papua New Guinea - PG",
    "Paraguay - PY",
    "Peru - PE",
    "Philippines - PH",
    "Poland - PL",
    "Portugal - PT",
    "Qatar - QA",
    "Romania - RO",
    "Russia - RU",
    "Rwanda - RW",
    "Saint Kitts and Nevis - KN",
    "Saint Lucia - LC",
    "Saint Vincent and the Grenadines - VC",
    "Samoa - WS",
    "San Marino - SM",
    "Sao Tome and Principe - ST",
    "Saudi Arabia - SA",
    "Senegal - SN",
    "Serbia - RS",
    "Seychelles - SC",
    "Sierra Leone - SL",
    "Singapore - SG",
    "Slovakia - SK",
    "Slovenia - SI",
    "Solomon Islands - SB",
    "Somalia - SO",
    "South Africa - ZA",
    "South Sudan - SS",
    "Spain - ES",
    "Sri Lanka - LK",
    "Sudan - SD",
    "Suriname - SR",
    "Sweden - SE",
    "Switzerland - CH",
    "Syria - SY",
    "Tajikistan - TJ",
    "Tanzania - TZ",
    "Thailand - TH",
    "Timor-Leste - TL",
    "Togo - TG",
    "Tonga - TO",
    "Trinidad and Tobago - TT",
    "Tunisia - TN",
    "Turkey - TR",
    "Turkmenistan - TM",
    "Tuvalu - TV",
    "Uganda - UG",
    "Ukraine - UA",
    "United Arab Emirates - AE",
    "United Kingdom - GB",
    "United States - US",
    "Uruguay - UY",
    "Uzbekistan - UZ",
    "Vanuatu - VU",
    "Vatican City - VA",
    "Venezuela - VE",
    "Vietnam - VN",
    "Yemen - YE",
    "Zambia - ZM",
    "Zimbabwe - ZW"


)
